### PR TITLE
Upgrade to CakePHP 3.0

### PR DESCRIPTION
**Pull request by rochamarcelo**
Hi, I've send  you a e-mail about upgrading to cakephp 3, so here is my pull request, I'm already using.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
:clap:

**Comment by jippi** [comment]
looks good - think we should target it a new branch called cake3 :)

**Comment by lorenzo** [comment]
I think master is fine, we create a 2.x branch, tag the latest commit and merge this

**Comment by jippi** [comment]
oki doki then

**Comment by rochamarcelo** [comment]
How are we? Need any fix?

**Comment by lorenzo** [comment]
I'll make some time today to merge this @rochamarcelo

**Comment by bravo-kernel** [comment]
This would be very welcome

**Comment by lorenzo** [comment]
@rochamarcelo Thanks a lot!

**Comment by bravo-kernel** [comment]
:clap:

**Pull request merged**
