### PR TITLE
passing the audit_id to afterAuditCreate method

### PR DESCRIPTION
**Pull request by pedrofs**
I would like to have the audit_id in this method.

What do you think about it?

Best,
Pedro.

### CODE REVIEW

**Comment by pedrofs** [comment]
And what do you think about creating Issues for this project? :)

**Comment by lorenzo** [comment]
This project is likely to be abandoned. I suggest using https://github.com/lorenzo/audit-stash

**Comment by pedrofs** [comment]
Good. Seems a great plugin. I'll take a look.

Thanks @lorenzo 

Anyway, for now you can't merge it, right?

Best,
Pedro.

**Comment by lorenzo** [comment]
@pedrofs A small change, now that you want this merged... can you pass the entity instead of just the id?

**Comment by pedrofs** [comment]
@lorenzo done :)

Thanks!

**Pull request merged**
